### PR TITLE
empty line in prefixfile do not cause problems anymore

### LINKED ISSUE #196: Fails if prefix-file contains an empty line
If the prefix file included in a template contains an empty line, jekyll fails with the following error:

```
/tmp/Jekyll-RDF/.vendor/bundle/ruby/2.3.0/gems/jekyll-rdf-3.0.0.pre.develop.485/lib/jekyll/helper/rdf_general_helper.rb:75:in `block in load_prefixes': undefined method `[]' for nil:NilClass (NoMethodError)
	from /tmp/Jekyll-RDF/.vendor/bundle/ruby/2.3.0/gems/jekyll-rdf-3.0.0.pre.develop.485/lib/jekyll/helper/rdf_general_helper.rb:73:in `collect'
	from /tmp/Jekyll-RDF/.vendor/bundle/ruby/2.3.0/gems/jekyll-rdf-3.0.0.pre.develop.485/lib/jekyll/helper/rdf_general_helper.rb:73:in `load_prefixes'
	from /tmp/Jekyll-RDF/.vendor/bundle/ruby/2.3.0/gems/jekyll-rdf-3.0.0.pre.develop.485/lib/jekyll/helper/rdf_prefix_helper.rb:35:in `load_prefixes'
	from /tmp/Jekyll-RDF/.vendor/bundle/ruby/2.3.0/gems/jekyll-rdf-3.0.0.pre.develop.485/lib/jekyll/helper/rdf_page_helper.rb:101:in `load_prefixes_yaml'
	from /tmp/Jekyll-RDF/.vendor/bundle/ruby/2.3.0/gems/jekyll-rdf-3.0.0.pre.develop.485/lib/jekyll/helper/rdf_page_helper.rb:31:in `re_init_as_rdf'
	from /tmp/Jekyll-RDF/.vendor/bundle/ruby/2.3.0/gems/jekyll-rdf-3.0.0.pre.develop.485/lib/jekyll/helper/rdf_generator_helper.rb:127:in `create_page'
	from /tmp/Jekyll-RDF/.vendor/bundle/ruby/2.3.0/gems/jekyll-rdf-3.0.0.pre.develop.485/lib/jekyll/helper/rdf_generator_helper.rb:11:in `block in prepare_pages'
	from /tmp/Jekyll-RDF/.vendor/bundle/ruby/2.3.0/gems/jekyll-rdf-3.0.0.pre.develop.485/lib/jekyll/helper/rdf_generator_helper.rb:8:in `each'
	from /tmp/Jekyll-RDF/.vendor/bundle/ruby/2.3.0/gems/jekyll-rdf-3.0.0.pre.develop.485/lib/jekyll/helper/rdf_generator_helper.rb:8:in `prepare_pages'
	from /tmp/Jekyll-RDF/.vendor/bundle/ruby/2.3.0/gems/jekyll-rdf-3.0.0.pre.develop.485/lib/jekyll/rdf_main_generator.rb:68:in `generate'
	from /tmp/Jekyll-RDF/.vendor/bundle/ruby/2.3.0/gems/jekyll-3.8.3/lib/jekyll/site.rb:175:in `block in generate'
	from /tmp/Jekyll-RDF/.vendor/bundle/ruby/2.3.0/gems/jekyll-3.8.3/lib/jekyll/site.rb:173:in `each'
	from /tmp/Jekyll-RDF/.vendor/bundle/ruby/2.3.0/gems/jekyll-3.8.3/lib/jekyll/site.rb:173:in `generate'
	from /tmp/Jekyll-RDF/.vendor/bundle/ruby/2.3.0/gems/jekyll-3.8.3/lib/jekyll/site.rb:70:in `process'
	from /tmp/Jekyll-RDF/.vendor/bundle/ruby/2.3.0/gems/jekyll-3.8.3/lib/jekyll/command.rb:28:in `process_site'
	from /tmp/Jekyll-RDF/.vendor/bundle/ruby/2.3.0/gems/jekyll-3.8.3/lib/jekyll/commands/build.rb:65:in `build'
	from /tmp/Jekyll-RDF/.vendor/bundle/ruby/2.3.0/gems/jekyll-3.8.3/lib/jekyll/commands/build.rb:36:in `process'
	from /tmp/Jekyll-RDF/.vendor/bundle/ruby/2.3.0/gems/jekyll-3.8.3/lib/jekyll/commands/serve.rb:93:in `block in start'
	from /tmp/Jekyll-RDF/.vendor/bundle/ruby/2.3.0/gems/jekyll-3.8.3/lib/jekyll/commands/serve.rb:93:in `each'
	from /tmp/Jekyll-RDF/.vendor/bundle/ruby/2.3.0/gems/jekyll-3.8.3/lib/jekyll/commands/serve.rb:93:in `start'
	from /tmp/Jekyll-RDF/.vendor/bundle/ruby/2.3.0/gems/jekyll-3.8.3/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
	from /tmp/Jekyll-RDF/.vendor/bundle/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /tmp/Jekyll-RDF/.vendor/bundle/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /tmp/Jekyll-RDF/.vendor/bundle/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /tmp/Jekyll-RDF/.vendor/bundle/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /tmp/Jekyll-RDF/.vendor/bundle/ruby/2.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /tmp/Jekyll-RDF/.vendor/bundle/ruby/2.3.0/gems/jekyll-3.8.3/exe/jekyll:15:in `<top (required)>'
	from /tmp/Jekyll-RDF/.vendor/bundle/ruby/2.3.0/bin/jekyll:22:in `load'
	from /tmp/Jekyll-RDF/.vendor/bundle/ruby/2.3.0/bin/jekyll:22:in `<main>'
```

### PR DESCRIPTION
**Pull request by Simaris**
Fix #196.

### CODE REVIEW

File: lib/jekyll/helper/rdf_general_helper.rb [hunk 1]
```diff
@@ -72,8 +72,9 @@ def self.load_prefixes(path, prefHolder)
             prefHolder["rdf_prefixes"] = prefix_file.join(" ")
             prefHolder["rdf_prefix_map"] = Hash[ *(prefix_file.collect { |v|
                   arr = v.split(":",2)
+                  next [nil, nil] if arr[1].nil?
                   [arr[0][7..-1].strip, arr[1].strip[1..-2]]
-                }.flatten)]
+                }.flatten.select {|x| !x.nil?})]
```
Comment (white-gecko) [inline lib/jekyll/helper/rdf_general_helper.rb]: please use reject instead of select

**Comment by Simaris** [comment]
@white-gecko I have implemented the reject instead of the select method
