### PR TITLE
default templates are not mandantory anymore

### LINKED ISSUE #49: Manual: Integrate with Jekyll does not work without template
Trying to follow the Manual I get for step 3: Integrate with Jekyll
```
$ jekyll build
Configuration file: /home/franz/workspace/jekyll-rdf/my_page/_config.yml
               Source: /home/franz/workspace/jekyll-rdf/my_page
               Destination: /home/franz/workspace/jekyll-rdf/my_page/_site
               Incremental build: disabled. Enable with --incremental
      Generating... 
jekyll 3.1.0 | Error:  no implicit conversion of nil into String
```

Do I need a mandatory mapping template (default template) to run jekyll build?

### PR DESCRIPTION
**Pull request by Simaris**
Fixes #49

### CODE REVIEW

File: lib/jekyll/rdf_main_generator.rb [hunk 1]
```diff
@@ -100,18 +100,18 @@ def generate(site)
         if(entry['./'].nil?)
```
Comment (Simaris) [inline lib/jekyll/rdf_main_generator.rb]: test
